//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Collections.Generic;
    
    public partial class ITartificialintelligence
    {
        public int id { get; set; }
        public string title { get; set; }
        public string abstracts { get; set; }
        public string keywords { get; set; }
        public string inspec { get; set; }
        public string inspecnot { get; set; }
        public string ieeeterms { get; set; }
        public string label { get; set; }
        public string search { get; set; }
    }
}
