//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsFormsApplication1
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LWEntities7 : DbContext
    {
        public LWEntities7()
            : base("name=LWEntities7")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DZelectricalsystem> DZelectricalsystem { get; set; }
        public virtual DbSet<DZelectricalsystemurl> DZelectricalsystemurl { get; set; }
        public virtual DbSet<DZoptoelectronicdevice> DZoptoelectronicdevice { get; set; }
        public virtual DbSet<DZoptoelectronicdeviceurl> DZoptoelectronicdeviceurl { get; set; }
        public virtual DbSet<HXchemicalelement> HXchemicalelement { get; set; }
        public virtual DbSet<HXchemicalelementurl> HXchemicalelementurl { get; set; }
        public virtual DbSet<HXfinechemicals> HXfinechemicals { get; set; }
        public virtual DbSet<HXfinechemicalsurl> HXfinechemicalsurl { get; set; }
        public virtual DbSet<HXmoleculardesign> HXmoleculardesign { get; set; }
        public virtual DbSet<HXmoleculardesignurl> HXmoleculardesignurl { get; set; }
        public virtual DbSet<HXorganicsynthesis> HXorganicsynthesis { get; set; }
        public virtual DbSet<HXorganicsynthesisurl> HXorganicsynthesisurl { get; set; }
        public virtual DbSet<ITartificialintelligence> ITartificialintelligence { get; set; }
        public virtual DbSet<ITartificialintelligenceurl> ITartificialintelligenceurl { get; set; }
        public virtual DbSet<ITmachinelearning> ITmachinelearning { get; set; }
        public virtual DbSet<ITmachinelearningurl> ITmachinelearningurl { get; set; }
        public virtual DbSet<ITparallelcomputing> ITparallelcomputing { get; set; }
        public virtual DbSet<ITparallelcomputingurl> ITparallelcomputingurl { get; set; }
        public virtual DbSet<SXcombinatorialmathematics> SXcombinatorialmathematics { get; set; }
        public virtual DbSet<SXcombinatorialmathematicsurl> SXcombinatorialmathematicsurl { get; set; }
        public virtual DbSet<SXfunctionalanalysis> SXfunctionalanalysis { get; set; }
        public virtual DbSet<SXfunctionalanalysisurl> SXfunctionalanalysisurl { get; set; }
        public virtual DbSet<SXfunctiontheory> SXfunctiontheory { get; set; }
        public virtual DbSet<SXfunctiontheoryurl> SXfunctiontheoryurl { get; set; }
        public virtual DbSet<SXordinarydifferential> SXordinarydifferential { get; set; }
        public virtual DbSet<SXordinarydifferentialurl> SXordinarydifferentialurl { get; set; }
        public virtual DbSet<TXintegratedcircuit> TXintegratedcircuit { get; set; }
        public virtual DbSet<TXintegratedcircuiturl> TXintegratedcircuiturl { get; set; }
        public virtual DbSet<TXmobilecommunication> TXmobilecommunication { get; set; }
        public virtual DbSet<TXmobilecommunicationurl> TXmobilecommunicationurl { get; set; }
        public virtual DbSet<TXopticalfiber> TXopticalfiber { get; set; }
        public virtual DbSet<TXopticalfiberurl> TXopticalfiberurl { get; set; }
        public virtual DbSet<TXsignalprocessing> TXsignalprocessing { get; set; }
        public virtual DbSet<TXsignalprocessingurl> TXsignalprocessingurl { get; set; }
    }
}
